### ISSUE TITLE
https://jravilab.org/ and https://jravilab.org/molevolvr are unavailable

### ISSUE THREAD

**Issue by lcolladotor** [JRaviLab/jravilab.github.io#1]
Hi,

I'm aware that this is not the best place to report this, but I couldn't find a better public repository for this report. But https://jravilab.org/ and https://jravilab.org/molevolvr are both unavailable.

```
This site can’t be reachedjravilab.org refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED
```

Best,
Leo

**Comment by lcolladotor** [comment]
AHH, I think that the issue is between https and http. The http version of the URLs do work, unlike the https ones.

http://jravilab.org/
http://jravilab.org/molevolvr/

**Comment by jananiravi** [comment]
Good catch, @lcolladotor. Could you tell me where you found the `https`  links? I can replace them with `http`. thanks!
